REM python ./src/use_libraries/anytree/main.py
REM python ./src/use_libraries/bitstring/main.py
REM python ./src/use_libraries/deap/main_one_max_bin.py
REM python ./src/ea_node/main_compact_horizontal.py
REM python ./src/ea_node/main_compact_vertical.py
REM python ./src/ea_node/main_is_equal.py
REM python ./src/ea_node/main_random_init.py
REM python ./src/ea_node/main_rearange_by_label.py
REM python ./src/ea_node/main_rearange.py
REM python ./src/ea_node/dollo_node/main_random_init.py